from tkinter import *
root = Tk()
root.geometry("500x1000")
root.title('Tkinter')
label_0 =Label(root,text="Registration form", width=20,font=("bold",20))
label_0.place(x=80,y=60)
label_1 =Label(root,text="FullName", width=20,font=("bold",10))
label_1.place(x=80,y=130)
entry_1=Entry(root)
entry_1.place(x=240,y=130)
label_2 =Label(root,text="Reg No", width=20,font=("bold",10))
label_2.place(x=68,y=180)
entry_2=Entry(root)
entry_2.place(x=240,y=180)
label_3=Label(root,text="Email",width=20,font=("bold",10))
label_3.place(x=70,y=230)
entry_3=Entry(root)
entry_3.place(x=240,y=230)
label_4 =Label(root,text="Gender", width=20,font=("bold",10))
label_4.place(x=70,y=280)
var=IntVar()
Radiobutton(root,text="Female",padx=5, variable= var, value=1).place(x=235,y=280)
Radiobutton(root,text="Male",padx=5, variable= var, value=2).place(x=290,y=280)
label_5=Label(root,text="Branch",width=20,font=("bold",10))
label_5.place(x=70,y=330)
list_of_country=[ 'BE' ,'BTech' , 'ME' ,'MTech' ,'other']
c=StringVar()
droplist=OptionMenu(root,c, *list_of_country)
droplist.config(width=15)
c.set('Select your Branch')
droplist.place(x=240,y=330)
label_6=Label(root,text="Department",width=20,font=("bold",10))
label_6.place(x=70,y=380)
list_of_country=[ 'IT' ,'CSE' , 'EEE' ,'ECE' ,'other']
c=StringVar()
droplist=OptionMenu(root,c, *list_of_country)
droplist.config(width=15)
c.set('Select your Department')
droplist.place(x=240,y=380)
label_7=Label(root,text="Languages Known",width=20,font=('bold',10))
label_7.place(x=70,y=430)
var1=IntVar()
Checkbutton(root,text="C", variable=var1).place(x=230,y=430)
var2=IntVar()
Checkbutton(root,text="C++", variable=var2).place(x=290,y=430)
var3=IntVar()
Checkbutton(root,text="Java",variable=var3).place(x=345,y=430)
var4=IntVar()
Checkbutton(root,text="python",variable=var3).place(x=400,y=430)
Button(root, text='Submit' , width=20,bg="black",fg='white').place(x=180,y=580)
root.mainloop()